name: Nightly

on:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
    - 'scripts/**'
    - 'poly/**'
    - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nim
      run: curl https://nim-lang.org/download/nim-1.6.6_x64.zip -o nim.zip
      tar --strip-components 1 -xf nim.zip

    - name: Build
      run: .\nim.exe -d:release --opt:size c capybara.nim

    - name: GitHub Release
      run: |
        git tag -d nightly || true
        git push origin --delete nightly || true
        git tag nightly
        git push origin nightly
        gh release delete ${{ env.VERSION }} -y || true
        gh release create ${{ env.VERSION }} -t "Nightly" -n "$(git rev-parse HEAD | cut -c 1-7) | $(git log -1 --pretty=%B)" ${{ env.FILES }}
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        VERSION: 'nightly'
        FILES: capybara.exe